version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  app:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
    ports:
      - "8000:8000"  # if exposing later 